import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "fr" | "en" | "es" | "pt";

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "es", label: "Español", flag: "🇪🇸" },
  { code: "pt", label: "Português", flag: "🇧🇷" },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    if (saved && ["fr", "en", "es", "pt"].includes(saved)) return saved as Language;
    return "fr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    const keys = key.split(".");
    let value: any = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    if (typeof value === "string") return value;
    // Fallback to French
    value = translations.fr;
    for (const k of keys) {
      value = value?.[k];
    }
    return typeof value === "string" ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

const translations: Record<Language, Record<string, any>> = {
  fr: {
    common: {
      back: "Retour",
      loading: "Chargement…",
      error: "Erreur",
      or: "ou",
      send: "Envoyer",
      cancel: "Annuler",
    },
    header: {
      title: "Assistant Catholique",
      subtitle: "8 experts à votre service",
      plans: "Plans",
      support: "Soutenir",
      history: "Historique",
    },
    landing: {
      poweredByAI: "Propulsé par l'Intelligence Artificielle",
      heroTitle1: "Explorez la foi catholique",
      heroTitle2: "avec 8 experts",
      heroTitle3: "théologiques",
      heroDesc: "Posez n'importe quelle question sur la foi, la morale, la liturgie ou l'histoire de l'Église. Recevez une réponse complète, documentée et fidèle au Magistère.",
      startFree: "Commencer gratuitement",
      discoverFeatures: "Découvrir les fonctionnalités",
      expertsAI: "Experts IA",
      yearsDoctrine: "Ans de doctrine",
      availability: "Disponibilité",
      featuresTitle: "Tout ce dont vous avez besoin",
      featuresDesc: "Une plateforme complète pour approfondir votre connaissance de la foi catholique.",
      testimonialsTitle: "Ce que disent nos utilisateurs",
      testimonialsDesc: "Des milliers de fidèles, prêtres et catéchistes font déjà confiance à notre plateforme.",
      pricingTitle: "Commencez gratuitement",
      pricingDesc: "3 consultations gratuites par jour. Passez au Premium pour en profiter davantage.",
      createFreeAccount: "Créer un compte gratuit",
      copyright: "Assistant de Recherche Catholique. Tous droits réservés.",
      login: "Connexion",
      start: "Commencer",
    },
    features: {
      experts: { title: "8 Experts Théologiques", desc: "Un panel d'experts couvrant la Bible, le Catéchisme, la Patristique, la Liturgie et plus encore." },
      sources: { title: "Sources Authentiques", desc: "Chaque réponse est fondée sur les textes officiels de l'Église catholique." },
      voice: { title: "Dictée & Lecture Vocale", desc: "Posez vos questions à la voix et écoutez les réponses grâce à la synthèse vocale." },
      fidelity: { title: "Fidélité au Magistère", desc: "Un orchestrateur IA garantit la cohérence doctrinale de chaque consultation." },
      chatbot: { title: "Chatbot Assistant", desc: "Un assistant IA disponible 24h/24 pour répondre à vos questions de foi." },
      accessible: { title: "Accessible Partout", desc: "Consultez depuis n'importe quel appareil, à tout moment, où que vous soyez." },
    },
    testimonials: {
      t1: { name: "Père Jean-Marie", role: "Curé de paroisse", text: "Un outil remarquable pour préparer mes homélies. Les analyses croisées des experts me font gagner un temps précieux." },
      t2: { name: "Sœur Thérèse", role: "Religieuse enseignante", text: "Mes élèves adorent poser des questions et découvrir la richesse de la foi catholique de manière interactive." },
      t3: { name: "Marc D.", role: "Catéchiste laïc", text: "Enfin un outil fiable qui cite ses sources ! Je l'utilise chaque semaine pour préparer mes séances de catéchèse." },
      t4: { name: "Claire L.", role: "Étudiante en théologie", text: "La qualité des réponses est impressionnante. C'est comme avoir accès à une bibliothèque théologique complète." },
    },
    plans: {
      basic: "Basique",
      premium: "Premium",
      elite: "Elite",
      free: "Gratuit",
      perDay: "consultations/jour",
      unlimited: "Consultations illimitées",
      popular: "Populaire",
      currentPlan: "Plan actuel",
      subscribe: "S'abonner",
      choosePlan: "Choisissez votre plan",
      choosePlanDesc: "Accédez à la sagesse de nos experts selon vos besoins",
      activeUntil: "Abonnement actif jusqu'au",
      supportMonastery: "Soutenir le Monastère Sainte Marie de Bouaké",
      supportMonasteryDesc: "Participez librement aux œuvres de la communauté monastique",
    },
    auth: {
      loginTitle: "Connectez-vous pour accéder à vos consultations",
      signupTitle: "Créez votre compte",
      continueWithGoogle: "Continuer avec Google",
      displayName: "Nom d'affichage",
      yourName: "Votre nom",
      email: "Email",
      password: "Mot de passe",
      forgotPassword: "Mot de passe oublié ?",
      login: "Se connecter",
      signup: "S'inscrire",
      noAccount: "Pas encore de compte ?",
      hasAccount: "Déjà un compte ?",
      checkEmail: "Vérifiez votre email pour confirmer votre inscription.",
      authError: "Erreur d'authentification",
      googleError: "Erreur de connexion Google",
    },
    index: {
      welcome: "Bienvenue, cher ami",
      welcomeDesc: "Explorez la richesse de la foi catholique avec nos",
      experts: "8 experts",
      welcomeDesc2: "à votre service.",
      analyzePhase: "Analyse de la question par l'Orchestrateur assistant en chef…",
      selectPhase: "Sélection des experts pertinents…",
      consultPhase: "Consultation de {count} expert(s)…",
      synthesisPhase: "Synthèse en cours…",
      placeholder: "Posez votre question sur la foi catholique…",
      speaking: "Parlez maintenant…",
      limitReached: "Vous avez atteint la limite de {limit} consultations/jour. Passez à un plan supérieur !",
      listen: "Écouter",
      stop: "Stop",
      vocal: "Vocal",
    },
    themes: {
      exploreByTheme: "Explorer par thème",
      theology: { title: "Théologie", desc: "Dogmes, Trinité, sacrements", s1: "Qu'est-ce que la Trinité ?", s2: "Expliquez la transsubstantiation" },
      liturgy: { title: "Liturgie", desc: "Messe, rites, temps liturgiques", s1: "Comment se déroule la messe ?", s2: "Que signifie le temps de l'Avent ?" },
      scripture: { title: "Écriture Sainte", desc: "Bible, Évangiles, exégèse", s1: "Que dit l'Évangile sur le pardon ?", s2: "Comment interpréter la Genèse ?" },
      spiritual: { title: "Vie spirituelle", desc: "Prière, discernement, saints", s1: "Comment prier le chapelet ?", s2: "Qu'est-ce que le discernement ignatien ?" },
      moral: { title: "Morale & Éthique", desc: "Conscience, vertus, bioéthique", s1: "Que dit l'Église sur la bioéthique ?", s2: "Comment former sa conscience morale ?" },
      historyTheme: { title: "Histoire", desc: "Conciles, papes, grandes figures", s1: "Quels furent les grands conciles ?", s2: "Qui était saint Augustin ?" },
    },
    faq: {
      title: "Questions fréquentes",
      q1: "Qu'est-ce que l'Assistant Catholique ?",
      a1: "C'est un outil d'intelligence artificielle qui consulte 8 experts spécialisés (théologie, droit canon, liturgie, Bible, morale, histoire, patristique et vie monastique) pour répondre à vos questions sur la foi catholique avec rigueur et nuance.",
      q2: "Les réponses sont-elles fiables ?",
      a2: "Les réponses s'appuient sur les sources du Magistère, des Pères de l'Église et de la Tradition. Cependant, elles ne remplacent pas l'accompagnement d'un prêtre ou d'un directeur spirituel.",
      q3: "Comment fonctionne la consultation des experts ?",
      a3: "Lorsque vous posez une question, un orchestrateur analyse votre demande et sélectionne les experts les plus pertinents. Chacun apporte sa contribution spécialisée, puis une synthèse harmonieuse est produite.",
      q4: "Puis-je utiliser la fonctionnalité vocale ?",
      a4: "Oui ! Cliquez sur l'icône de microphone pour dicter votre question. Vous pouvez aussi écouter les réponses en cliquant sur l'icône de haut-parleur.",
      q5: "Mon historique est-il sauvegardé ?",
      a5: "Oui, toutes vos consultations sont sauvegardées dans votre espace personnel via le bouton « Historique ».",
    },
    history: {
      title: "Historique des consultations",
      empty: "Aucune consultation sauvegardée.",
      askQuestion: "Poser une question",
      collapse: "Réduire",
      experts: "expert(s)",
      loadError: "Erreur lors du chargement de l'historique",
      deleteError: "Erreur lors de la suppression",
      deleted: "Consultation supprimée",
    },
    donation: {
      title: "Soutenir le Monastère",
      heading: "Libre don pour le Monastère",
      description: "Participez librement aux œuvres et à la vie du Monastère Sainte Marie de Bouaké. Votre générosité soutient la communauté monastique et ses missions.",
      chooseAmount: "Choisissez un montant ou entrez le vôtre",
      customAmount: "Ou entrez un montant libre",
      amountPlaceholder: "Montant",
      yourDonation: "Votre don :",
      donate: "Faire un don",
      minAmount: "Le montant minimum est de 100 XOF ou 1 USD",
      currencyLabel: "Devise",
      securePayment: "Paiement sécurisé via Paystack. L'application reste entièrement gratuite.",
      thankYou: "Merci pour votre générosité !",
      thankYouDesc: "Votre don soutient les œuvres et la vie du Monastère Sainte Marie de Bouaké. Que le Seigneur vous bénisse pour votre générosité.",
      backToAssistant: "Retour à l'assistant",
      anotherDonation: "Faire un autre don",
    },
    chatbot: {
      title: "Chat Assistant",
      placeholder: "Votre question…",
      emptyState: "Posez-moi une question rapide sur la foi catholique ✝️",
      thinking: "Réflexion…",
      connectionError: "Erreur de connexion",
    },
  },

  en: {
    common: {
      back: "Back",
      loading: "Loading…",
      error: "Error",
      or: "or",
      send: "Send",
      cancel: "Cancel",
    },
    header: {
      title: "Catholic Assistant",
      subtitle: "8 experts at your service",
      plans: "Plans",
      support: "Support",
      history: "History",
    },
    landing: {
      poweredByAI: "Powered by Artificial Intelligence",
      heroTitle1: "Explore the Catholic faith",
      heroTitle2: "with 8 theological",
      heroTitle3: "experts",
      heroDesc: "Ask any question about faith, morality, liturgy, or Church history. Receive a complete, documented answer faithful to the Magisterium.",
      startFree: "Start for free",
      discoverFeatures: "Discover features",
      expertsAI: "AI Experts",
      yearsDoctrine: "Years of doctrine",
      availability: "Availability",
      featuresTitle: "Everything you need",
      featuresDesc: "A comprehensive platform to deepen your knowledge of the Catholic faith.",
      testimonialsTitle: "What our users say",
      testimonialsDesc: "Thousands of faithful, priests and catechists already trust our platform.",
      pricingTitle: "Start for free",
      pricingDesc: "3 free consultations per day. Upgrade to Premium for more.",
      createFreeAccount: "Create a free account",
      copyright: "Catholic Research Assistant. All rights reserved.",
      login: "Log in",
      start: "Get started",
    },
    features: {
      experts: { title: "8 Theological Experts", desc: "A panel of experts covering the Bible, Catechism, Patristics, Liturgy and more." },
      sources: { title: "Authentic Sources", desc: "Every answer is grounded in official texts of the Catholic Church." },
      voice: { title: "Voice Dictation & Reading", desc: "Ask your questions by voice and listen to answers with text-to-speech." },
      fidelity: { title: "Magisterium Fidelity", desc: "An AI orchestrator ensures the doctrinal consistency of each consultation." },
      chatbot: { title: "Chatbot Assistant", desc: "An AI assistant available 24/7 to answer your questions of faith." },
      accessible: { title: "Accessible Anywhere", desc: "Consult from any device, at any time, wherever you are." },
    },
    testimonials: {
      t1: { name: "Father Jean-Marie", role: "Parish priest", text: "A remarkable tool for preparing my homilies. The cross-analyses from experts save me precious time." },
      t2: { name: "Sister Thérèse", role: "Teaching nun", text: "My students love asking questions and discovering the richness of Catholic faith interactively." },
      t3: { name: "Marc D.", role: "Lay catechist", text: "Finally a reliable tool that cites its sources! I use it every week to prepare my catechesis sessions." },
      t4: { name: "Claire L.", role: "Theology student", text: "The quality of answers is impressive. It's like having access to a complete theological library." },
    },
    plans: {
      basic: "Basic",
      premium: "Premium",
      elite: "Elite",
      free: "Free",
      perDay: "consultations/day",
      unlimited: "Unlimited consultations",
      popular: "Popular",
      currentPlan: "Current plan",
      subscribe: "Subscribe",
      choosePlan: "Choose your plan",
      choosePlanDesc: "Access the wisdom of our experts according to your needs",
      activeUntil: "Subscription active until",
      supportMonastery: "Support the Monastery of Saint Mary of Bouaké",
      supportMonasteryDesc: "Freely participate in the works of the monastic community",
    },
    auth: {
      loginTitle: "Log in to access your consultations",
      signupTitle: "Create your account",
      continueWithGoogle: "Continue with Google",
      displayName: "Display name",
      yourName: "Your name",
      email: "Email",
      password: "Password",
      forgotPassword: "Forgot password?",
      login: "Log in",
      signup: "Sign up",
      noAccount: "Don't have an account?",
      hasAccount: "Already have an account?",
      checkEmail: "Check your email to confirm your registration.",
      authError: "Authentication error",
      googleError: "Google sign-in error",
    },
    index: {
      welcome: "Welcome, dear friend",
      welcomeDesc: "Explore the richness of the Catholic faith with our",
      experts: "8 experts",
      welcomeDesc2: "at your service.",
      analyzePhase: "Analyzing the question by the Chief Orchestrator Assistant…",
      selectPhase: "Selecting relevant experts…",
      consultPhase: "Consulting {count} expert(s)…",
      synthesisPhase: "Synthesis in progress…",
      placeholder: "Ask your question about the Catholic faith…",
      speaking: "Speak now…",
      limitReached: "You have reached the limit of {limit} consultations/day. Upgrade to a higher plan!",
      listen: "Listen",
      stop: "Stop",
      vocal: "Voice",
    },
    themes: {
      exploreByTheme: "Explore by theme",
      theology: { title: "Theology", desc: "Dogmas, Trinity, sacraments", s1: "What is the Trinity?", s2: "Explain transubstantiation" },
      liturgy: { title: "Liturgy", desc: "Mass, rites, liturgical seasons", s1: "How does the Mass proceed?", s2: "What does Advent mean?" },
      scripture: { title: "Holy Scripture", desc: "Bible, Gospels, exegesis", s1: "What does the Gospel say about forgiveness?", s2: "How to interpret Genesis?" },
      spiritual: { title: "Spiritual life", desc: "Prayer, discernment, saints", s1: "How to pray the rosary?", s2: "What is Ignatian discernment?" },
      moral: { title: "Morality & Ethics", desc: "Conscience, virtues, bioethics", s1: "What does the Church say about bioethics?", s2: "How to form one's moral conscience?" },
      historyTheme: { title: "History", desc: "Councils, popes, great figures", s1: "What were the great councils?", s2: "Who was Saint Augustine?" },
    },
    faq: {
      title: "Frequently asked questions",
      q1: "What is the Catholic Assistant?",
      a1: "It is an AI tool that consults 8 specialized experts (theology, canon law, liturgy, Bible, morality, history, patristics and monastic life) to answer your questions about the Catholic faith.",
      q2: "Are the answers reliable?",
      a2: "The answers are based on Magisterium sources, Church Fathers and Tradition. However, they do not replace guidance from a priest or spiritual director.",
      q3: "How does the expert consultation work?",
      a3: "When you ask a question, an orchestrator analyzes your request and selects the most relevant experts. Each provides their specialized contribution, then a harmonious synthesis is produced.",
      q4: "Can I use the voice feature?",
      a4: "Yes! Click the microphone icon to dictate your question. You can also listen to answers by clicking the speaker icon.",
      q5: "Is my history saved?",
      a5: "Yes, all your consultations are saved in your personal space via the 'History' button.",
    },
    history: {
      title: "Consultation history",
      empty: "No saved consultations.",
      askQuestion: "Ask a question",
      collapse: "Collapse",
      experts: "expert(s)",
      loadError: "Error loading history",
      deleteError: "Error deleting",
      deleted: "Consultation deleted",
    },
    donation: {
      title: "Support the Monastery",
      heading: "Free donation for the Monastery",
      description: "Freely participate in the works and life of the Monastery of Saint Mary of Bouaké. Your generosity supports the monastic community and its missions.",
      chooseAmount: "Choose an amount or enter your own",
      customAmount: "Or enter a custom amount (XOF)",
      amountPlaceholder: "Amount in XOF",
      yourDonation: "Your donation:",
      donate: "Donate",
      minAmount: "The minimum amount is 100 XOF",
      securePayment: "Secure payment via Paystack. The application remains entirely free.",
      thankYou: "Thank you for your generosity!",
      thankYouDesc: "Your donation supports the works and life of the Monastery of Saint Mary of Bouaké. May the Lord bless you for your generosity.",
      backToAssistant: "Back to assistant",
      anotherDonation: "Make another donation",
    },
    chatbot: {
      title: "Chat Assistant",
      placeholder: "Your question…",
      emptyState: "Ask me a quick question about the Catholic faith ✝️",
      thinking: "Thinking…",
      connectionError: "Connection error",
    },
  },

  es: {
    common: {
      back: "Volver",
      loading: "Cargando…",
      error: "Error",
      or: "o",
      send: "Enviar",
      cancel: "Cancelar",
    },
    header: {
      title: "Asistente Católico",
      subtitle: "8 expertos a su servicio",
      plans: "Planes",
      support: "Apoyar",
      history: "Historial",
    },
    landing: {
      poweredByAI: "Impulsado por Inteligencia Artificial",
      heroTitle1: "Explore la fe católica",
      heroTitle2: "con 8 expertos",
      heroTitle3: "teológicos",
      heroDesc: "Haga cualquier pregunta sobre la fe, la moral, la liturgia o la historia de la Iglesia. Reciba una respuesta completa, documentada y fiel al Magisterio.",
      startFree: "Comenzar gratis",
      discoverFeatures: "Descubrir funciones",
      expertsAI: "Expertos IA",
      yearsDoctrine: "Años de doctrina",
      availability: "Disponibilidad",
      featuresTitle: "Todo lo que necesita",
      featuresDesc: "Una plataforma completa para profundizar su conocimiento de la fe católica.",
      testimonialsTitle: "Lo que dicen nuestros usuarios",
      testimonialsDesc: "Miles de fieles, sacerdotes y catequistas ya confían en nuestra plataforma.",
      pricingTitle: "Comience gratis",
      pricingDesc: "3 consultas gratuitas por día. Pase a Premium para más.",
      createFreeAccount: "Crear una cuenta gratis",
      copyright: "Asistente de Investigación Católica. Todos los derechos reservados.",
      login: "Iniciar sesión",
      start: "Comenzar",
    },
    features: {
      experts: { title: "8 Expertos Teológicos", desc: "Un panel de expertos que cubre la Biblia, el Catecismo, la Patrística, la Liturgia y más." },
      sources: { title: "Fuentes Auténticas", desc: "Cada respuesta se basa en los textos oficiales de la Iglesia católica." },
      voice: { title: "Dictado y Lectura por Voz", desc: "Haga sus preguntas por voz y escuche las respuestas con síntesis de voz." },
      fidelity: { title: "Fidelidad al Magisterio", desc: "Un orquestador de IA garantiza la coherencia doctrinal de cada consulta." },
      chatbot: { title: "Chatbot Asistente", desc: "Un asistente de IA disponible 24/7 para responder sus preguntas de fe." },
      accessible: { title: "Accesible en Todas Partes", desc: "Consulte desde cualquier dispositivo, en cualquier momento, donde esté." },
    },
    testimonials: {
      t1: { name: "Padre Juan María", role: "Párroco", text: "Una herramienta notable para preparar mis homilías. Los análisis cruzados de expertos me ahorran tiempo valioso." },
      t2: { name: "Hermana Teresa", role: "Religiosa docente", text: "Mis alumnos adoran hacer preguntas y descubrir la riqueza de la fe católica de forma interactiva." },
      t3: { name: "Marc D.", role: "Catequista laico", text: "¡Por fin una herramienta fiable que cita sus fuentes! La uso cada semana para preparar mis sesiones de catequesis." },
      t4: { name: "Claire L.", role: "Estudiante de teología", text: "La calidad de las respuestas es impresionante. Es como tener acceso a una biblioteca teológica completa." },
    },
    plans: {
      basic: "Básico",
      premium: "Premium",
      elite: "Elite",
      free: "Gratis",
      perDay: "consultas/día",
      unlimited: "Consultas ilimitadas",
      popular: "Popular",
      currentPlan: "Plan actual",
      subscribe: "Suscribirse",
      choosePlan: "Elija su plan",
      choosePlanDesc: "Acceda a la sabiduría de nuestros expertos según sus necesidades",
      activeUntil: "Suscripción activa hasta",
      supportMonastery: "Apoyar el Monasterio Santa María de Bouaké",
      supportMonasteryDesc: "Participe libremente en las obras de la comunidad monástica",
    },
    auth: {
      loginTitle: "Inicie sesión para acceder a sus consultas",
      signupTitle: "Cree su cuenta",
      continueWithGoogle: "Continuar con Google",
      displayName: "Nombre visible",
      yourName: "Su nombre",
      email: "Correo",
      password: "Contraseña",
      forgotPassword: "¿Olvidó su contraseña?",
      login: "Iniciar sesión",
      signup: "Registrarse",
      noAccount: "¿No tiene cuenta?",
      hasAccount: "¿Ya tiene cuenta?",
      checkEmail: "Verifique su correo para confirmar su registro.",
      authError: "Error de autenticación",
      googleError: "Error de inicio de sesión con Google",
    },
    index: {
      welcome: "Bienvenido, querido amigo",
      welcomeDesc: "Explore la riqueza de la fe católica con nuestros",
      experts: "8 expertos",
      welcomeDesc2: "a su servicio.",
      analyzePhase: "Analizando la pregunta por el Orquestador asistente jefe…",
      selectPhase: "Seleccionando expertos relevantes…",
      consultPhase: "Consultando {count} experto(s)…",
      synthesisPhase: "Síntesis en curso…",
      placeholder: "Haga su pregunta sobre la fe católica…",
      speaking: "Hable ahora…",
      limitReached: "Ha alcanzado el límite de {limit} consultas/día. ¡Pase a un plan superior!",
      listen: "Escuchar",
      stop: "Parar",
      vocal: "Voz",
    },
    themes: {
      exploreByTheme: "Explorar por tema",
      theology: { title: "Teología", desc: "Dogmas, Trinidad, sacramentos", s1: "¿Qué es la Trinidad?", s2: "Explique la transubstanciación" },
      liturgy: { title: "Liturgia", desc: "Misa, ritos, tiempos litúrgicos", s1: "¿Cómo se desarrolla la misa?", s2: "¿Qué significa el Adviento?" },
      scripture: { title: "Sagrada Escritura", desc: "Biblia, Evangelios, exégesis", s1: "¿Qué dice el Evangelio sobre el perdón?", s2: "¿Cómo interpretar el Génesis?" },
      spiritual: { title: "Vida espiritual", desc: "Oración, discernimiento, santos", s1: "¿Cómo rezar el rosario?", s2: "¿Qué es el discernimiento ignaciano?" },
      moral: { title: "Moral y Ética", desc: "Conciencia, virtudes, bioética", s1: "¿Qué dice la Iglesia sobre la bioética?", s2: "¿Cómo formar la conciencia moral?" },
      historyTheme: { title: "Historia", desc: "Concilios, papas, grandes figuras", s1: "¿Cuáles fueron los grandes concilios?", s2: "¿Quién fue San Agustín?" },
    },
    faq: {
      title: "Preguntas frecuentes",
      q1: "¿Qué es el Asistente Católico?",
      a1: "Es una herramienta de IA que consulta 8 expertos especializados para responder sus preguntas sobre la fe católica con rigor y matiz.",
      q2: "¿Son fiables las respuestas?",
      a2: "Las respuestas se basan en fuentes del Magisterio, Padres de la Iglesia y la Tradición. Sin embargo, no reemplazan la guía de un sacerdote.",
      q3: "¿Cómo funciona la consulta de expertos?",
      a3: "Al hacer una pregunta, un orquestador analiza su solicitud y selecciona los expertos más relevantes para producir una síntesis armoniosa.",
      q4: "¿Puedo usar la función de voz?",
      a4: "¡Sí! Haga clic en el icono del micrófono para dictar su pregunta. También puede escuchar las respuestas.",
      q5: "¿Se guarda mi historial?",
      a5: "Sí, todas sus consultas se guardan en su espacio personal mediante el botón 'Historial'.",
    },
    history: {
      title: "Historial de consultas",
      empty: "No hay consultas guardadas.",
      askQuestion: "Hacer una pregunta",
      collapse: "Reducir",
      experts: "experto(s)",
      loadError: "Error al cargar el historial",
      deleteError: "Error al eliminar",
      deleted: "Consulta eliminada",
    },
    donation: {
      title: "Apoyar el Monasterio",
      heading: "Donación libre para el Monasterio",
      description: "Participe libremente en las obras y la vida del Monasterio Santa María de Bouaké.",
      chooseAmount: "Elija un monto o ingrese el suyo",
      customAmount: "O ingrese un monto libre (XOF)",
      amountPlaceholder: "Monto en XOF",
      yourDonation: "Su donación:",
      donate: "Donar",
      minAmount: "El monto mínimo es 100 XOF",
      securePayment: "Pago seguro vía Paystack. La aplicación es totalmente gratuita.",
      thankYou: "¡Gracias por su generosidad!",
      thankYouDesc: "Su donación apoya las obras del Monasterio Santa María de Bouaké. Que el Señor lo bendiga.",
      backToAssistant: "Volver al asistente",
      anotherDonation: "Hacer otra donación",
    },
    chatbot: {
      title: "Chat Asistente",
      placeholder: "Su pregunta…",
      emptyState: "Hágame una pregunta rápida sobre la fe católica ✝️",
      thinking: "Reflexionando…",
      connectionError: "Error de conexión",
    },
  },

  pt: {
    common: {
      back: "Voltar",
      loading: "Carregando…",
      error: "Erro",
      or: "ou",
      send: "Enviar",
      cancel: "Cancelar",
    },
    header: {
      title: "Assistente Católico",
      subtitle: "8 especialistas ao seu serviço",
      plans: "Planos",
      support: "Apoiar",
      history: "Histórico",
    },
    landing: {
      poweredByAI: "Impulsionado por Inteligência Artificial",
      heroTitle1: "Explore a fé católica",
      heroTitle2: "com 8 especialistas",
      heroTitle3: "teológicos",
      heroDesc: "Faça qualquer pergunta sobre fé, moral, liturgia ou história da Igreja. Receba uma resposta completa, documentada e fiel ao Magistério.",
      startFree: "Começar grátis",
      discoverFeatures: "Descobrir funcionalidades",
      expertsAI: "Especialistas IA",
      yearsDoctrine: "Anos de doutrina",
      availability: "Disponibilidade",
      featuresTitle: "Tudo o que precisa",
      featuresDesc: "Uma plataforma completa para aprofundar o seu conhecimento da fé católica.",
      testimonialsTitle: "O que dizem os nossos utilizadores",
      testimonialsDesc: "Milhares de fiéis, padres e catequistas já confiam na nossa plataforma.",
      pricingTitle: "Comece grátis",
      pricingDesc: "3 consultas gratuitas por dia. Passe para Premium para mais.",
      createFreeAccount: "Criar conta grátis",
      copyright: "Assistente de Pesquisa Católica. Todos os direitos reservados.",
      login: "Entrar",
      start: "Começar",
    },
    features: {
      experts: { title: "8 Especialistas Teológicos", desc: "Um painel de especialistas cobrindo Bíblia, Catecismo, Patrística, Liturgia e mais." },
      sources: { title: "Fontes Autênticas", desc: "Cada resposta é fundamentada nos textos oficiais da Igreja católica." },
      voice: { title: "Ditado e Leitura por Voz", desc: "Faça suas perguntas por voz e ouça as respostas com síntese de voz." },
      fidelity: { title: "Fidelidade ao Magistério", desc: "Um orquestrador de IA garante a coerência doutrinal de cada consulta." },
      chatbot: { title: "Chatbot Assistente", desc: "Um assistente de IA disponível 24/7 para responder às suas perguntas de fé." },
      accessible: { title: "Acessível em Todo Lugar", desc: "Consulte de qualquer dispositivo, a qualquer momento, onde estiver." },
    },
    testimonials: {
      t1: { name: "Padre João Maria", role: "Pároco", text: "Uma ferramenta notável para preparar minhas homilias. As análises cruzadas dos especialistas me poupam tempo precioso." },
      t2: { name: "Irmã Teresa", role: "Religiosa professora", text: "Meus alunos adoram fazer perguntas e descobrir a riqueza da fé católica de forma interativa." },
      t3: { name: "Marc D.", role: "Catequista leigo", text: "Finalmente uma ferramenta confiável que cita suas fontes! Uso toda semana para preparar minhas sessões de catequese." },
      t4: { name: "Claire L.", role: "Estudante de teologia", text: "A qualidade das respostas é impressionante. É como ter acesso a uma biblioteca teológica completa." },
    },
    plans: {
      basic: "Básico",
      premium: "Premium",
      elite: "Elite",
      free: "Grátis",
      perDay: "consultas/dia",
      unlimited: "Consultas ilimitadas",
      popular: "Popular",
      currentPlan: "Plano atual",
      subscribe: "Assinar",
      choosePlan: "Escolha seu plano",
      choosePlanDesc: "Acesse a sabedoria dos nossos especialistas conforme suas necessidades",
      activeUntil: "Assinatura ativa até",
      supportMonastery: "Apoiar o Mosteiro Santa Maria de Bouaké",
      supportMonasteryDesc: "Participe livremente nas obras da comunidade monástica",
    },
    auth: {
      loginTitle: "Entre para acessar suas consultas",
      signupTitle: "Crie sua conta",
      continueWithGoogle: "Continuar com Google",
      displayName: "Nome de exibição",
      yourName: "Seu nome",
      email: "Email",
      password: "Senha",
      forgotPassword: "Esqueceu a senha?",
      login: "Entrar",
      signup: "Cadastrar",
      noAccount: "Não tem conta?",
      hasAccount: "Já tem conta?",
      checkEmail: "Verifique seu email para confirmar seu cadastro.",
      authError: "Erro de autenticação",
      googleError: "Erro de login com Google",
    },
    index: {
      welcome: "Bem-vindo, caro amigo",
      welcomeDesc: "Explore a riqueza da fé católica com nossos",
      experts: "8 especialistas",
      welcomeDesc2: "ao seu serviço.",
      analyzePhase: "Analisando a pergunta pelo Orquestrador assistente chefe…",
      selectPhase: "Selecionando especialistas relevantes…",
      consultPhase: "Consultando {count} especialista(s)…",
      synthesisPhase: "Síntese em andamento…",
      placeholder: "Faça sua pergunta sobre a fé católica…",
      speaking: "Fale agora…",
      limitReached: "Você atingiu o limite de {limit} consultas/dia. Mude para um plano superior!",
      listen: "Ouvir",
      stop: "Parar",
      vocal: "Voz",
    },
    themes: {
      exploreByTheme: "Explorar por tema",
      theology: { title: "Teologia", desc: "Dogmas, Trindade, sacramentos", s1: "O que é a Trindade?", s2: "Explique a transubstanciação" },
      liturgy: { title: "Liturgia", desc: "Missa, ritos, tempos litúrgicos", s1: "Como se desenrola a missa?", s2: "O que significa o Advento?" },
      scripture: { title: "Sagrada Escritura", desc: "Bíblia, Evangelhos, exegese", s1: "O que diz o Evangelho sobre o perdão?", s2: "Como interpretar o Gênesis?" },
      spiritual: { title: "Vida espiritual", desc: "Oração, discernimento, santos", s1: "Como rezar o rosário?", s2: "O que é o discernimento inaciano?" },
      moral: { title: "Moral e Ética", desc: "Consciência, virtudes, bioética", s1: "O que diz a Igreja sobre bioética?", s2: "Como formar a consciência moral?" },
      historyTheme: { title: "História", desc: "Concílios, papas, grandes figuras", s1: "Quais foram os grandes concílios?", s2: "Quem foi Santo Agostinho?" },
    },
    faq: {
      title: "Perguntas frequentes",
      q1: "O que é o Assistente Católico?",
      a1: "É uma ferramenta de IA que consulta 8 especialistas para responder suas perguntas sobre a fé católica com rigor e nuance.",
      q2: "As respostas são confiáveis?",
      a2: "As respostas são baseadas em fontes do Magistério, Padres da Igreja e Tradição. No entanto, não substituem a orientação de um padre.",
      q3: "Como funciona a consulta de especialistas?",
      a3: "Ao fazer uma pergunta, um orquestrador analisa seu pedido e seleciona os especialistas mais relevantes para produzir uma síntese harmoniosa.",
      q4: "Posso usar a função de voz?",
      a4: "Sim! Clique no ícone do microfone para ditar sua pergunta. Você também pode ouvir as respostas.",
      q5: "Meu histórico é salvo?",
      a5: "Sim, todas as suas consultas são salvas no seu espaço pessoal pelo botão 'Histórico'.",
    },
    history: {
      title: "Histórico de consultas",
      empty: "Nenhuma consulta salva.",
      askQuestion: "Fazer uma pergunta",
      collapse: "Reduzir",
      experts: "especialista(s)",
      loadError: "Erro ao carregar o histórico",
      deleteError: "Erro ao excluir",
      deleted: "Consulta excluída",
    },
    donation: {
      title: "Apoiar o Mosteiro",
      heading: "Doação livre para o Mosteiro",
      description: "Participe livremente nas obras e vida do Mosteiro Santa Maria de Bouaké.",
      chooseAmount: "Escolha um valor ou insira o seu",
      customAmount: "Ou insira um valor livre (XOF)",
      amountPlaceholder: "Valor em XOF",
      yourDonation: "Sua doação:",
      donate: "Doar",
      minAmount: "O valor mínimo é 100 XOF",
      securePayment: "Pagamento seguro via Paystack. O aplicativo é totalmente gratuito.",
      thankYou: "Obrigado pela sua generosidade!",
      thankYouDesc: "Sua doação apoia as obras do Mosteiro Santa Maria de Bouaké. Que o Senhor o abençoe.",
      backToAssistant: "Voltar ao assistente",
      anotherDonation: "Fazer outra doação",
    },
    chatbot: {
      title: "Chat Assistente",
      placeholder: "Sua pergunta…",
      emptyState: "Faça-me uma pergunta rápida sobre a fé católica ✝️",
      thinking: "Refletindo…",
      connectionError: "Erro de conexão",
    },
  },
};
